version: '3.7'

services:

  ctaql-django-local:
    restart: always
    image: ctaql-django-local
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    entrypoint: /start.sh
