version: '3.7'

services:

  ctaql-django-local:
    restart: always
    image: ctaql-django-local
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    entrypoint: /code/docker/start.sh
