version: '3.7'

services:

  ctaql-postgres-local:
    restart: always
    image: postgres
    env_file:
      - .env
    volumes:
      - ./docker/local/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ctaql-django-local:
    restart: always
    image: ctaql-django-local
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 5000:3000
    links:
      - ctaql-postgres-local
    depends_on:
      - ctaql-postgres-local
    entrypoint: /code/docker/local/django/start.sh
