#!/bin/sh

# use the django manage.py command from within a docker container from shell on host

ARGS="$@"

docker-compose exec ctaql-django-local sh -c "cd /code && pipenv run python application/manage.py $ARGS"
